name: Hello World

on:
  push:
    branches:
      - main
      - develop

jobs:
  hello-world:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Print Hello World
        run: echo 'Hello World'

